### PR TITLE
Update shared module

### PR DESCRIPTION
**Pull request by veziak**

### CODE REVIEW

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-25 17:00:35 (UTC)</summary>
  <details><summary>Policy violation for <b>modules - digger plan</b></summary>
  User motatoes is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-26 08:59:30 (UTC)</summary>
  <details><summary>Policy violation for <b>modules - digger plan</b></summary>
  User motatoes is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-26 15:39:36 (UTC)</summary>
  <details><summary>Policy violation for <b>modules - digger plan</b></summary>
  User Spartakovic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-26 15:41:48 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User Spartakovic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-26 15:41:58 (UTC)</summary>
  <details><summary>Policy violation for <b>dev - digger plan</b></summary>
  User Spartakovic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-26 16:49:12 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#modules</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (modules)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by veziak** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-26 16:54:41 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#modules</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (modules)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by veziak** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-27 08:51:21 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#modules</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (modules)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Spartakovic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-27 08:59:24 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#modules</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (modules)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Spartakovic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-27 09:28:14 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#modules</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (modules)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Spartakovic** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-27 11:08:57 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#modules</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (modules)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-27 11:11:28 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#dev</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource_dev will be created
  + resource "null_resource" "test_resource_dev" {
      + id = (known after apply)
    }

  # module.mod_dev.null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # module.mod_dev.null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (dev)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-27 11:11:46 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource_prod will be created
  + resource "null_resource" "test_resource_prod" {
      + id = (known after apply)
    }

  # module.mod_prod.null_resource.test_resource will be created
  + resource "null_resource" "test_resource" {
      + id = (known after apply)
    }

  # module.mod_prod.null_resource.test_resource2 will be created
  + resource "null_resource" "test_resource2" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Pull request closed without merging**
