### PR TITLE
update vpc

### PR DESCRIPTION
**Pull request by motatoes**

### CODE REVIEW

**Comment by motatoes** [comment]
digger plan

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-09-27 11:44:40 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#dev_vpc</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.vpc_resource will be created
  + resource "null_resource" "vpc_resource" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (dev_vpc)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-09-27 11:45:13 (UTC)</summary>
  <details><summary>Error during init.</summary>
  
```terraform

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../modules: no such file or
directory


Error: Unreadable module directory

The directory  could not be read for module "mod_prod" at main.tf:2.


  ```
</details>
</details>

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-09-27 11:45:09 (UTC)</summary>
  <details><summary>Error during init.</summary>
  
```terraform

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../modules: no such file or
directory


Error: Unreadable module directory

The directory  could not be read for module "mod_dev" at main.tf:2.


  ```
</details>
</details>

**Pull request closed without merging**
