### PR TITLE
vpc update

### PR DESCRIPTION
**Pull request by motatoes**

### CODE REVIEW

**Comment by motatoes** [comment]
digger plan

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-09-27 11:49:43 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#dev_vpc</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.vpc will be created
  + resource "null_resource" "vpc" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (dev_vpc)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-09-27 11:50:11 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#dev</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource_dev will be created
  + resource "null_resource" "test_resource_dev" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (dev)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-09-27 11:50:15 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/parallel_jobs_demo#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_resource_prod will be created
  + resource "null_resource" "test_resource_prod" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Pull request closed without merging**
